tasks:
  - init: pip install -r requirements.txt
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - donjayamanne.githistory@0.6.9:ZuSpHC+Smmz7WQRRorLS0A==
    - mhutchie.git-graph@1.25.0:cok5Nd5YVi4j6T88HvR2QQ==